### ISSUE TITLE
Question before doing an Arabic translation

### ISSUE THREAD

**Issue by nader8** [iGio90/PokeMesh_Translations#9]
Hi, cool app.
I'm planning on doing an Arabic translation, but just before i start i want to make sure first that it is gonna work, because of the right-to-left thingy. So let me know.

**Comment by iGio90** [comment]
it will work without any problem. Android support RTL!

**Comment by nader8** [comment]
Fantastic , will start now :)

**Comment by iGio90** [comment]
Thanks :)
